name: Blog Posts

on:
  # Run workflow automatically
  schedule:
    # Runs every hour, on the hour
    - cron: '0 * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rishabkumar7/blog-post-workflow@master
        with:
          # comma-separated list of RSS feed urls
          feed_list: "https://blog.rishabkumar.com/rss.xml"
